### ISSUE TITLE
index 266 is out of bounds for axis 0 with size 264

### ISSUE THREAD

**Issue by x12901** [vicoslab/mixed-segdec-net-comind2021#30]
Problems when using my own dataset. How can I annotation  multi-tagged images?Is it possible to use pseudo-color annotation like paddle?https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/data/marker/marker.md

Directory structure

COCO

--IMAGE

--LABEL

```shell
D:\mixed-segdec-net-comind2021-master\mixed-segdec-net-comind2021-master>python -u train_net.py  --GPU=1 --DATASET=COCO --RUN_NAME=COCO --DATASET_PATH=datasets/COCO --RESULTS_PATH=save/results --SAVE_IMAGES=True --DILATE=7 --EPOCHS=50 --LEARNING_RATE=1.0 --DELTA_CLS_LOSS=0.01 --BATCH_SIZE=1 --WEIGHTED_SEG_LOSS=True --WEIGHTED_SEG_LOSS_P=2 --WEIGHTED_SEG_LOSS_MAX=1 --DYN_BALANCED_LOSS=True --GRADIENT_ADJUSTMENT=True --FREQUENCY_SAMPLING=True  --NUM_SEGMENTED=0 --FOLD=2
COCO Executing run with path save/results\COCO\COCO
COCO BATCH_SIZE                : 1
COCO DATASET                   : COCO
COCO DATASET_PATH              : datasets/COCO
COCO DELTA_CLS_LOSS            : 0.01
COCO DILATE                    : 7
COCO DYN_BALANCED_LOSS         : True
COCO EPOCHS                    : 50
COCO FOLD                      : 2
COCO FREQUENCY_SAMPLING        : True
COCO GPU                       : 1
COCO GRADIENT_ADJUSTMENT       : True
COCO INPUT_CHANNELS            : 1
COCO INPUT_HEIGHT              : 400
COCO INPUT_WIDTH               : 2448
COCO LEARNING_RATE             : 1.0
COCO MEMORY_FIT                : 1
COCO NUM_SEGMENTED             : 0
COCO ON_DEMAND_READ            : False
COCO REPRODUCIBLE_RUN          : False
COCO RESULTS_PATH              : save/results
COCO SAVE_IMAGES               : True
COCO TRAIN_NUM                 : None
COCO USE_BEST_MODEL            : False
COCO VALIDATE                  : True
COCO VALIDATE_ON_TEST          : True
COCO VALIDATION_N_EPOCHS       : 5
COCO WEIGHTED_SEG_LOSS         : True
COCO WEIGHTED_SEG_LOSS_MAX     : 1.0
COCO WEIGHTED_SEG_LOSS_P       : 2.0
datasets/COCO
268
264
536
datasets/COCO
268
264
532
536
536
COCO Saving current model state to save/results\COCO\COCO\models\ep_00.pth
COCO Returning seg_loss_weight 1.0 and dec_loss_weight 0.0
COCO Returning dec_gradient_multiplier 0
Traceback (most recent call last):
  File "train_net.py", line 63, in <module>
    end2end.train()
  File "D:\mixed-segdec-net-comind2021-master\mixed-segdec-net-comind2021-master\end2end.py", line 60, in train
    train_results = self._train_model(device, model, train_loader, loss_seg, loss_dec, optimizer, validation_loader, tensorboard_writer)
  File "D:\mixed-segdec-net-comind2021-master\mixed-segdec-net-comind2021-master\end2end.py", line 160, in _train_model
    for iter_index, (data) in enumerate(train_loader):
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\mixed-segdec-net-comind2021-master\mixed-segdec-net-comind2021-master\data\dataset.py", line 49, in __getitem__
    ix = self.neg_imgs_permutation[ix]
IndexError: index 266 is out of bounds for axis 0 with size 264

```

input_coco.py

```python
class COCODataset(Dataset):
    def __init__(self, kind: str, cfg):
        super(COCODataset, self).__init__(cfg.DATASET_PATH, cfg, kind)
        self.read_contents()

    def read_contents(self):
        pos_samples, neg_samples = [], []
        print(self.path)
        img_num = 0
        for image_name in glob.glob(self.path + '/IMAGE/*.jpg'):
            img_num += 1
            image_path = image_name
            image = self.read_img_resize(image_path, self.grayscale, self.image_size)
            img_name_short = image_name[:-4]
            jpg_name = img_name_short.split('\\')[-1]
            seg_mask_path = os.path.join(self.path, "LABEL", f"{jpg_name}.jpg")
            if os.path.exists(seg_mask_path):
                seg_mask, _ = self.read_label_resize(seg_mask_path, self.image_size, dilate=self.cfg.DILATE)
                image = self.to_tensor(image)
                seg_loss_mask = self.distance_transform(seg_mask, self.cfg.WEIGHTED_SEG_LOSS_MAX,
                                                        self.cfg.WEIGHTED_SEG_LOSS_P)
                seg_mask = self.to_tensor(self.downsize(seg_mask))
                seg_loss_mask = self.to_tensor(self.downsize(seg_loss_mask))
                pos_samples.append((image, seg_mask, seg_loss_mask, True, image_path, None, img_name_short))
            else:
                seg_mask = np.zeros_like(image)
                image = self.to_tensor(image)
                seg_loss_mask = self.to_tensor(self.downsize(np.ones_like(seg_mask)))
                seg_mask = self.to_tensor(self.downsize(seg_mask))
                neg_samples.append((image, seg_mask, seg_loss_mask, True, image_path, seg_mask_path, img_name_short))
        self.pos_samples = pos_samples
        self.neg_samples = neg_samples
        self.num_pos = len(pos_samples)
        print(len(pos_samples))
        self.num_neg = len(neg_samples)
        print(len(neg_samples))
        self.len = 2 * len(pos_samples) if self.kind in ['TRAIN'] else len(pos_samples) + len(neg_samples)
        print(self.len)
        self.init_extra()
```

**Comment by AnikaP** [comment]
I had a same exception (different context though), fixed it with #35
