### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by haloxing** [vicoslab/mixed-segdec-net-comind2021#37]
Traceback (most recent call last):
  File "D:\project\mixed-segdec-net-comind2021-master\train_net.py", line 63, in <module>
    end2end.train()
  File "D:\project\mixed-segdec-net-comind2021-master\end2end.py", line 41, in train
    self.print_run_params()
  File "D:\project\mixed-segdec-net-comind2021-master\end2end.py", line 363, in print_run_params
    k, v = l.split(":")
ValueError: too many values to unpack (expected 2)

I want to get the solution about this code error.

**Comment by skokec** [comment]
Hi, it is possible that the name or value in your configuration settings contains ":" which causes issue with the print_run_params function. You can just disable this function or change the separator at line 362-363 in [end2end2.py](https://github.com/vicoslab/mixed-segdec-net-comind2021/blob/21583eb22e719a70fee388ce45f0f7f27f529926/end2end.py#L362) to something more unique:

```
for l in sorted(map(lambda e: e[0] + "#$#" + str(e[1]) + "\n", self.cfg.get_as_dict().items())):
    k, v = l.split("#$#")
````

**Comment by haloxing** [comment]
It can be solved,thank you.
